import { ThemeProvider } from "next-themes";
import "./globals.scss";
import { ReduxProvider } from "../redux/provider";

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className=''>
        <ThemeProvider attribute='data-theme' defaultTheme='system' enableSystem>
          <ReduxProvider>
            {children}
          </ReduxProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
